server:
  port: 8206

mybatis-plus:
  type-enums-package: com.xie.ssyx.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-user?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  redis:
    host: 192.168.12.128
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

minio:
  accessKey: minio
  secretKey: minio123
  bucket: ssyx
  endpoint: http://192.168.12.128:9000
  readPath: http://192.168.12.128:9000

wx:
  open:
    # 小程序微信公众平台appId
    app_id: wx1c5e064fa3a82a6b
    # 小程序微信公众平台api秘钥
    app_secret: 9bc0449dc3824f8e08243b9187ef3550